on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: generate pdf
        run: npm run generate-pdf:ci
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/resume_en.pdf public/resume_fr.pdf
          git commit -m "generated pdf [skip ci]"
          git push